### ISSUE TITLE
Missing AddInvoiceRequest?

### ISSUE THREAD

**Issue by MrHash** [ndeet/php-ln-lnd-grpc#2]
Seems to be a missing class?

**Comment by ndeet** [comment]
Did not test but according to the `rpc.proto` the class is called `Invoice` as you see here in typehint between parantheses:
https://github.com/ndeet/php-ln-lnd-grpc/blob/master/rpc.proto#L437

The class is here: 
https://github.com/ndeet/php-ln-lnd-grpc/blob/master/src/Lnrpc/Invoice.php

Compare e.g. with `ListInvoices` where they properly named it `ListInvoiceRequest`:
https://github.com/ndeet/php-ln-lnd-grpc/blob/master/rpc.proto#L455

So this is caused by inconsistency (or maybe intended) naming of LND gRPC definitions.

**Comment by MrHash** [comment]
ok thanks, will close for now then
